name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

concurrency:
  group: build-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aemiii91/miyoomini-toolchain:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Copy submodule
        run: make copy-submodule
      - name: Apply patches
        run: make apply-patches
      - name: Assemble project
        run: make assemble
      - name: Build project
        run: make build
