name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aemiii91/miyoomini-toolchain:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build project
        shell: bash
        run: |
          source /root/.bashrc
          make build
